version: '3.4'

services:
  munerdoc-api:
    container_name: muner_doc_api
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "5000:8080"
  client:
    container_name: muner_doc_client
    ports:
      - "5001:3000"
  proxy:
    container_name: muner_doc_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" 
    restart: always
  
  
